export type BioluminescenceSceneParameters = {
  particleCount: 256 | 1024 | 4096 | 16384;
  particleSize: number;
  particleWakeStrength: number;
  particleDrag: number;
  particleNoiseStrength: number;
  particleNoiseFrequency: number;
  particleNoiseDrag: number;
  particleGravity: number;
  activationScale: number;
  activationSpeed: number;
  densityResX: number;
  densityResY: number;
  densityResZ: number;
  particleDensityStrength: number;
  fieldResX: number;
  fieldResY: number;
  fieldResZ: number;
  fieldDissipation: number;
  fieldSplatStrength: number;
  fieldSplatRadius: number;
  bubbleSizeMin: number;
  bubbleSizeMax: number;
  bubbleGravity: number;
  bubbleViscosity: number;
  bubbleSpawnRate: number;
  bubbleSpawnArea: number;
  bubbleAutoEmit: boolean;
  bubbleColor: string;
  bubbleDriftStrength: number;
  bubbleDriftFrequency: number;
  bubbleDriftDrag: number;
  bubbleRepelStrength: number;
  bubbleRepelRadius: number;
  bubbleWakeStrength: number;
  bubbleWakeLength: number;
  bubbleWakeAngle: number;
  energyAccumulationRate: number;
  energyDecayRate: number;
  activationEnergyThreshold: number;
  activationDuration: number;
  refractoryPeriod: number;
  sparkleMin: number;
  sparkleMax: number;
  volumeWidth: number;
  volumeHeight: number;
  volumeDepth: number;
  showVolume: boolean;
  baseColor: string;
  activeColor: string;
  baseAlpha: number;
  activeAlpha: number;
  emissiveStrength: number;
  bloomStrength: number;
  bloomRadius: number;
  bloomThreshold: number;
  backgroundColor: string;
};

export const BIOLUMINESCENCE_SCENE_DEFAULTS: BioluminescenceSceneParameters = {
  particleCount: 4096,
  particleSize: 0.03,
  particleWakeStrength: 0.6,
  particleDrag: 1.0,
  particleNoiseStrength: 0.1,
  particleNoiseFrequency: 0.6,
  particleNoiseDrag: 0.5,
  particleGravity: 0.0,
  activationScale: 3.0,
  activationSpeed: 1.0,
  densityResX: 32,
  densityResY: 16,
  densityResZ: 32,
  particleDensityStrength: 0.3,
  fieldResX: 64,
  fieldResY: 32,
  fieldResZ: 64,
  fieldDissipation: 0.98,
  fieldSplatStrength: 1.0,
  fieldSplatRadius: 0.3,
  bubbleSizeMin: 2.0,
  bubbleSizeMax: 6.0,
  bubbleGravity: 9.81,
  bubbleViscosity: 0.5,
  bubbleSpawnRate: 20.0,
  bubbleSpawnArea: 0.0,
  bubbleAutoEmit: false,
  bubbleColor: '#ffffff',
  bubbleDriftStrength: 0.0,
  bubbleDriftFrequency: 0.5,
  bubbleDriftDrag: 1.2,
  bubbleRepelStrength: 0.8,
  bubbleRepelRadius: 0.08,
  bubbleWakeStrength: 0.5,
  bubbleWakeLength: 1.0,
  bubbleWakeAngle: 0.5,
  energyAccumulationRate: 0.1,
  energyDecayRate: 0.02,
  activationEnergyThreshold: 1.0,
  activationDuration: 0.5,
  refractoryPeriod: 1.0,
  sparkleMin: 0.5,
  sparkleMax: 1.4,
  volumeWidth: 6.0,
  volumeHeight: 4.0,
  volumeDepth: 6.0,
  showVolume: false,
  baseColor: '#00bcd4',
  activeColor: '#7dffb0',
  baseAlpha: 0.2,
  activeAlpha: 0.95,
  emissiveStrength: 1.6,
  bloomStrength: 1.0,
  bloomRadius: 0.5,
  bloomThreshold: 0.1,
  backgroundColor: '#000000',
};
