// Type stubs for Three.js WebGPU/TSL entry points and JSM modules.
// These modules ship as plain JS in three r171+ but lack separate .d.ts files.
// We use `any` throughout so both value and type usage works.

// 'three' base package – used as `import * as THREE from 'three'`
// Declaring all exports as `any` lets TypeScript accept every usage pattern.
declare module 'three' {
  export type Scene = any;
  export type PerspectiveCamera = any;
  export type OrthographicCamera = any;
  export type Mesh = any;
  export type InstancedMesh = any;
  export type Group = any;
  export type Object3D = any;
  export type Color = any;
  export type Vector2 = any;
  export type Vector3 = any;
  export type Vector4 = any;
  export type Matrix4 = any;
  export type Euler = any;
  export type Quaternion = any;
  export type Texture = any;
  export type DataTexture = any;
  export type CanvasTexture = any;
  export type VideoTexture = any;
  export type Data3DTexture = any;
  export type DataArrayTexture = any;
  export type BufferGeometry = any;
  export type PlaneGeometry = any;
  export type BoxGeometry = any;
  export type SphereGeometry = any;
  export type IcosahedronGeometry = any;
  export type TorusGeometry = any;
  export type CylinderGeometry = any;
  export type ShapeGeometry = any;
  export type EdgesGeometry = any;
  export type WireframeGeometry = any;
  export type Shape = any;
  export type DirectionalLight = any;
  export type AmbientLight = any;
  export type PointLight = any;
  export type HemisphereLight = any;
  export type Material = any;
  export type MeshBasicMaterial = any;
  export type MeshStandardMaterial = any;
  export type ShaderMaterial = any;
  export type LineSegments = any;
  export type Line = any;
  export type LineBasicMaterial = any;
  export type Points = any;
  export type PointsMaterial = any;
  export type Sprite = any;
  export type SpriteMaterial = any;
  export type BufferAttribute = any;
  export type Float32BufferAttribute = any;
  export type Uint16BufferAttribute = any;
  export type Uint32BufferAttribute = any;
  export type InstancedBufferAttribute = any;
  export type Clock = any;
  export type Raycaster = any;
  export type Box3 = any;
  export type Sphere = any;
  export type Plane = any;
  export type Frustum = any;
  export type WebGLRenderTarget = any;
  export type PMREMGenerator = any;
  export type TextureLoader = any;
  export type CubeTextureLoader = any;
  export type AnimationMixer = any;
  export type Skeleton = any;
  export type SkinnedMesh = any;
  export type Bone = any;
  export type Loader = any;
  export type PostProcessing = any;
  export type WebGPURenderer = any;
  export type RenderTarget = any;
  export type Layers = any;

  export declare const Scene: new (...a: any[]) => any;
  export declare const PerspectiveCamera: new (...a: any[]) => any;
  export declare const OrthographicCamera: new (...a: any[]) => any;
  export declare const Mesh: new (...a: any[]) => any;
  export declare const InstancedMesh: new (...a: any[]) => any;
  export declare const Group: new (...a: any[]) => any;
  export declare const Object3D: new (...a: any[]) => any;
  export declare const Color: new (...a: any[]) => any;
  export declare const Vector2: new (...a: any[]) => any;
  export declare const Vector3: new (...a: any[]) => any;
  export declare const Vector4: new (...a: any[]) => any;
  export declare const Matrix4: new (...a: any[]) => any;
  export declare const Euler: new (...a: any[]) => any;
  export declare const Quaternion: new (...a: any[]) => any;
  export declare const Texture: new (...a: any[]) => any;
  export declare const DataTexture: new (...a: any[]) => any;
  export declare const CanvasTexture: new (...a: any[]) => any;
  export declare const VideoTexture: new (...a: any[]) => any;
  export declare const Data3DTexture: new (...a: any[]) => any;
  export declare const DataArrayTexture: new (...a: any[]) => any;
  export declare const BufferGeometry: new (...a: any[]) => any;
  export declare const PlaneGeometry: new (...a: any[]) => any;
  export declare const BoxGeometry: new (...a: any[]) => any;
  export declare const SphereGeometry: new (...a: any[]) => any;
  export declare const IcosahedronGeometry: new (...a: any[]) => any;
  export declare const TorusGeometry: new (...a: any[]) => any;
  export declare const CylinderGeometry: new (...a: any[]) => any;
  export declare const ShapeGeometry: new (...a: any[]) => any;
  export declare const EdgesGeometry: new (...a: any[]) => any;
  export declare const WireframeGeometry: new (...a: any[]) => any;
  export declare const Shape: new (...a: any[]) => any;
  export declare const DirectionalLight: new (...a: any[]) => any;
  export declare const AmbientLight: new (...a: any[]) => any;
  export declare const PointLight: new (...a: any[]) => any;
  export declare const HemisphereLight: new (...a: any[]) => any;
  export declare const Material: any;
  export declare const MeshBasicMaterial: new (...a: any[]) => any;
  export declare const MeshStandardMaterial: new (...a: any[]) => any;
  export declare const ShaderMaterial: new (...a: any[]) => any;
  export declare const LineSegments: new (...a: any[]) => any;
  export declare const Line: new (...a: any[]) => any;
  export declare const LineBasicMaterial: new (...a: any[]) => any;
  export declare const Points: new (...a: any[]) => any;
  export declare const PointsMaterial: new (...a: any[]) => any;
  export declare const Sprite: new (...a: any[]) => any;
  export declare const SpriteMaterial: new (...a: any[]) => any;
  export declare const BufferAttribute: new (...a: any[]) => any;
  export declare const Float32BufferAttribute: new (...a: any[]) => any;
  export declare const Uint16BufferAttribute: new (...a: any[]) => any;
  export declare const Uint32BufferAttribute: new (...a: any[]) => any;
  export declare const InstancedBufferAttribute: new (...a: any[]) => any;
  export declare const Clock: new (...a: any[]) => any;
  export declare const Raycaster: new (...a: any[]) => any;
  export declare const Box3: new (...a: any[]) => any;
  export declare const Sphere: new (...a: any[]) => any;
  export declare const Plane: new (...a: any[]) => any;
  export declare const Frustum: new (...a: any[]) => any;
  export declare const WebGLRenderTarget: new (...a: any[]) => any;
  export declare const PMREMGenerator: new (...a: any[]) => any;
  export declare const TextureLoader: new (...a: any[]) => any;
  export declare const CubeTextureLoader: new (...a: any[]) => any;
  export declare const AnimationMixer: new (...a: any[]) => any;
  export declare const Skeleton: new (...a: any[]) => any;
  export declare const SkinnedMesh: new (...a: any[]) => any;
  export declare const Bone: new (...a: any[]) => any;
  export declare const Loader: new (...a: any[]) => any;
  export declare const PostProcessing: new (...a: any[]) => any;
  export declare const WebGPURenderer: new (...a: any[]) => any;
  export declare const RenderTarget: new (...a: any[]) => any;
  export declare const Layers: new (...a: any[]) => any;

  export const RGBAFormat: any;
  export const DoubleSide: any;
  export const FrontSide: any;
  export const BackSide: any;
  export const NearestFilter: any;
  export const LinearFilter: any;
  export const RepeatWrapping: any;
  export const ClampToEdgeWrapping: any;
  export const NormalBlending: any;
  export const AdditiveBlending: any;
  export const NoBlending: any;
  export const FloatType: any;
  export const HalfFloatType: any;
  export const UnsignedByteType: any;
  export const UnsignedIntType: any;
  export const SRGBColorSpace: any;
  export const LinearSRGBColorSpace: any;
  export const ACESFilmicToneMapping: any;
  export const LinearToneMapping: any;
  export const NoToneMapping: any;
  export const GLSL3: any;
  export const StaticDrawUsage: any;
  export const DynamicDrawUsage: any;
  export const PCFSoftShadowMap: any;
  export const PCFShadowMap: any;
  export const BasicShadowMap: any;
  export const MathUtils: any;
}

declare module 'three/webgpu' {
  export type WebGPURenderer = any;
  export type MeshBasicNodeMaterial = any;
  export type MeshStandardNodeMaterial = any;
  export type PostProcessing = any;
  export type StorageTexture = any;
  export type Storage3DTexture = any;
  export type StorageBufferAttribute = any;
  export type Scene = any;
  export type PerspectiveCamera = any;
  export type OrthographicCamera = any;
  export type DataTexture = any;
  export type Texture = any;
  export type CanvasTexture = any;
  export type Material = any;
  export type BufferGeometry = any;
  export type Mesh = any;
  export type Color = any;
  export type Vector2 = any;
  export type Vector3 = any;
  export type Vector4 = any;
  export type DirectionalLight = any;
  export type SphereGeometry = any;
  export type MeshBasicMaterial = any;
  export type Shape = any;

  export const WebGPURenderer: new (...args: any[]) => any;
  export const MeshBasicNodeMaterial: new (...args: any[]) => any;
  export const MeshStandardNodeMaterial: new (...args: any[]) => any;
  export const PostProcessing: new (...args: any[]) => any;
  export const StorageTexture: new (...args: any[]) => any;
  export const Storage3DTexture: new (...args: any[]) => any;
  export const StorageBufferAttribute: new (...args: any[]) => any;
  export const StorageInstancedBufferAttribute: new (...args: any[]) => any;
  export const Scene: new (...args: any[]) => any;
  export const PerspectiveCamera: new (...args: any[]) => any;
  export const OrthographicCamera: new (...args: any[]) => any;
  export const DataTexture: new (...args: any[]) => any;
  export const Data3DTexture: new (...args: any[]) => any;
  export const DepthTexture: new (...args: any[]) => any;
  export const Texture: new (...args: any[]) => any;
  export const CanvasTexture: new (...args: any[]) => any;
  export const Material: any;
  export const BufferGeometry: new (...args: any[]) => any;
  export const Mesh: new (...args: any[]) => any;
  export const Color: new (...args: any[]) => any;
  export const Vector2: new (...args: any[]) => any;
  export const Vector3: new (...args: any[]) => any;
  export const Vector4: new (...args: any[]) => any;
  export const Matrix4: new (...args: any[]) => any;
  export const Euler: new (...args: any[]) => any;
  export const Quaternion: new (...args: any[]) => any;
  export const DirectionalLight: new (...args: any[]) => any;
  export const AmbientLight: new (...args: any[]) => any;
  export const PointLight: new (...args: any[]) => any;
  export const HemisphereLight: new (...args: any[]) => any;
  export const PlaneGeometry: new (...args: any[]) => any;
  export const BoxGeometry: new (...args: any[]) => any;
  export const SphereGeometry: new (...args: any[]) => any;
  export const IcosahedronGeometry: new (...args: any[]) => any;
  export const TorusGeometry: new (...args: any[]) => any;
  export const CylinderGeometry: new (...args: any[]) => any;
  export const ShapeGeometry: new (...args: any[]) => any;
  export const Shape: new (...args: any[]) => any;
  export const MeshBasicMaterial: new (...args: any[]) => any;
  export const MeshStandardMaterial: new (...args: any[]) => any;
  export const ShaderMaterial: new (...args: any[]) => any;
  export const NodeMaterial: new (...args: any[]) => any;
  export const Points: new (...args: any[]) => any;
  export const PointsMaterial: new (...args: any[]) => any;
  export const Line: new (...args: any[]) => any;
  export const LineSegments: new (...args: any[]) => any;
  export const LineBasicMaterial: new (...args: any[]) => any;
  export const Group: new (...args: any[]) => any;
  export const Object3D: new (...args: any[]) => any;
  export const InstancedMesh: new (...args: any[]) => any;
  export const Sprite: new (...args: any[]) => any;
  export const SpriteMaterial: new (...args: any[]) => any;
  export const BufferAttribute: new (...args: any[]) => any;
  export const Float32BufferAttribute: new (...args: any[]) => any;
  export const Uint16BufferAttribute: new (...args: any[]) => any;
  export const Uint32BufferAttribute: new (...args: any[]) => any;
  export const InstancedBufferAttribute: new (...args: any[]) => any;
  export const Clock: new (...args: any[]) => any;
  export const Raycaster: new (...args: any[]) => any;
  export const Box3: new (...args: any[]) => any;
  export const Sphere: new (...args: any[]) => any;
  export const Plane: new (...args: any[]) => any;
  export const Frustum: new (...args: any[]) => any;
  export const WebGLRenderTarget: new (...args: any[]) => any;
  export const PMREMGenerator: new (...args: any[]) => any;
  export const TextureLoader: new (...args: any[]) => any;
  export const CubeTextureLoader: new (...args: any[]) => any;
  export const AnimationMixer: new (...args: any[]) => any;
  export const Skeleton: new (...args: any[]) => any;
  export const SkinnedMesh: new (...args: any[]) => any;
  export const Bone: new (...args: any[]) => any;
  export const RenderTarget: new (...args: any[]) => any;
  export const Layers: new (...args: any[]) => any;
  export const Group: new (...args: any[]) => any;
  export const Object3D: new (...args: any[]) => any;
  export type RenderTarget = any;
  export type Layers = any;
  export type Group = any;
  export type Object3D = any;
  export const VideoTexture: new (...args: any[]) => any;
  export const CompressedTexture: new (...args: any[]) => any;
  export const DataArrayTexture: new (...args: any[]) => any;
  export const MathUtils: any;
  export const RGBAFormat: any;
  export const RGBAIntegerFormat: any;
  export const DoubleSide: any;
  export const FrontSide: any;
  export const BackSide: any;
  export const NearestFilter: any;
  export const LinearFilter: any;
  export const RepeatWrapping: any;
  export const ClampToEdgeWrapping: any;
  export const NormalBlending: any;
  export const AdditiveBlending: any;
  export const NoBlending: any;
  export const FloatType: any;
  export const HalfFloatType: any;
  export const UnsignedByteType: any;
  export const UnsignedIntType: any;
  export const NearestMipMapLinearFilter: any;
  export const LinearMipMapLinearFilter: any;
  export const LoopOnce: any;
  export const LoopRepeat: any;
  export const SRGBColorSpace: any;
  export const LinearSRGBColorSpace: any;
  export const ACESFilmicToneMapping: any;
  export const LinearToneMapping: any;
  export const ReinhardToneMapping: any;
  export const NoToneMapping: any;
  export const GLSL3: any;
  export const StaticDrawUsage: any;
  export const DynamicDrawUsage: any;
  export const EquirectangularReflectionMapping: any;
  export const CubeReflectionMapping: any;
  export const CubeUVReflectionMapping: any;
  export const PCFSoftShadowMap: any;
  export const PCFShadowMap: any;
  export const BasicShadowMap: any;
  export const VSMShadowMap: any;
  export const ObjectSpaceNormalMap: any;
  export const TangentSpaceNormalMap: any;
}

declare module 'three/tsl' {
  export const uniform: any;
  export const texture: any;
  export const Fn: any;
  export const Loop: any;
  export const If: any;
  export const Break: any;
  export const Continue: any;
  export const Return: any;
  export const float: any;
  export const int: any;
  export const uint: any;
  export const bool: any;
  export const vec2: any;
  export const vec3: any;
  export const vec4: any;
  export const ivec2: any;
  export const ivec3: any;
  export const ivec4: any;
  export const uvec2: any;
  export const uvec3: any;
  export const uvec4: any;
  export const bvec2: any;
  export const bvec3: any;
  export const bvec4: any;
  export const mat2: any;
  export const mat3: any;
  export const mat4: any;
  export const color: any;
  export const storage: any;
  export const instancedArray: any;
  export const instanceIndex: any;
  export const vertexIndex: any;
  export const drawIndex: any;
  export const screenUV: any;
  export const uv: any;
  export const attribute: any;
  export const positionLocal: any;
  export const positionWorld: any;
  export const positionView: any;
  export const normalLocal: any;
  export const normalWorld: any;
  export const normalView: any;
  export const cameraPosition: any;
  export const cameraViewMatrix: any;
  export const cameraProjectionMatrix: any;
  export const modelMatrix: any;
  export const viewMatrix: any;
  export const projectionMatrix: any;
  export const select: any;
  export const pass: any;
  export const mrt: any;
  export const output: any;
  export const emissive: any;
  export const floor: any;
  export const ceil: any;
  export const fract: any;
  export const abs: any;
  export const sign: any;
  export const sin: any;
  export const cos: any;
  export const tan: any;
  export const asin: any;
  export const acos: any;
  export const atan: any;
  export const exp: any;
  export const exp2: any;
  export const log: any;
  export const log2: any;
  export const sqrt: any;
  export const inversesqrt: any;
  export const inverseSqrt: any;
  export const pow: any;
  export const min: any;
  export const max: any;
  export const clamp: any;
  export const mix: any;
  export const step: any;
  export const smoothstep: any;
  export const length: any;
  export const dot: any;
  export const cross: any;
  export const normalize: any;
  export const reflect: any;
  export const refract: any;
  export const distance: any;
  export const dFdx: any;
  export const dFdy: any;
  export const add: any;
  export const sub: any;
  export const mul: any;
  export const div: any;
  export const mod: any;
  export const modInt: any;
  export const remainder: any;
  export const bitAnd: any;
  export const bitOr: any;
  export const bitXor: any;
  export const bitNot: any;
  export const shiftLeft: any;
  export const shiftRight: any;
  export const lessThan: any;
  export const greaterThan: any;
  export const lessThanEqual: any;
  export const greaterThanEqual: any;
  export const equal: any;
  export const notEqual: any;
  export const and: any;
  export const or: any;
  export const not: any;
  export const cond: any;
  export const assign: any;
  export const hash: any;
  export const textureStore: any;
  export const textureLoad: any;
  export const sampler: any;
  export const sharedUniform: any;
  export const atomicAdd: any;
  export const atomicSub: any;
  export const atomicMax: any;
  export const atomicMin: any;
  export const atomicAnd: any;
  export const atomicOr: any;
  export const atomicXor: any;
  export const atomicStore: any;
  export const atomicLoad: any;
  export const barrier: any;
  export const workgroupBarrier: any;
  export const storageBarrier: any;
  export const workgroupId: any;
  export const localId: any;
  export const numWorkgroups: any;
  export const Var: any;
  export const NodeVar: any;
  export const attributeArray: any;
  export const texture3D: any;
  export const getViewPosition: any;
  export const interleavedGradientNoise: any;
  export const shadow: any;
  export const screenCoordinate: any;
}

declare module 'three/examples/jsm/controls/OrbitControls.js' {
  export class OrbitControls {
    constructor(camera: any, domElement?: HTMLElement);
    enabled: boolean;
    target: any;
    enableDamping: boolean;
    dampingFactor: number;
    enableZoom: boolean;
    enableRotate: boolean;
    enablePan: boolean;
    autoRotate: boolean;
    autoRotateSpeed: number;
    minDistance: number;
    maxDistance: number;
    minPolarAngle: number;
    maxPolarAngle: number;
    update(): void;
    dispose(): void;
    addEventListener(type: string, listener: (event: any) => void): void;
    removeEventListener(type: string, listener: (event: any) => void): void;
  }
}

declare module 'three/examples/jsm/tsl/display/BloomNode.js' {
  export function bloom(input: any, strength?: number, radius?: number, threshold?: number): any;
}

declare module 'three/examples/jsm/utils/BufferGeometryUtils.js' {
  export function mergeGeometries(geometries: any[], useGroups?: boolean): any;
  export function mergeVertices(geometry: any, tolerance?: number): any;
  export function toTrianglesDrawMode(geometry: any, drawMode: any): any;
}
